version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
